name: CI

on:
  push:
    branches: ["**"]
  pull_request:
  workflow_dispatch:

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Validate Gradle Wrapper
        uses: gradle/actions/wrapper-validation@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Setup Gradle (cache)
        uses: gradle/actions/setup-gradle@v4

      - name: Grant execute permission for Gradle wrapper
        run: chmod +x ./gradlew

      - name: Build, test, and verify coverage
        run: ./gradlew --no-daemon --stacktrace clean check jacocoTestReport

      - name: Upload unit test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results-${{ runner.os }}
          path: |
            build/test-results/test
            build/reports/tests/test
          if-no-files-found: ignore
          retention-days: 7

      - name: Upload JaCoCo coverage report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: jacoco-report-${{ runner.os }}
          path: |
            build/reports/jacoco/test/jacocoTestReport.xml
            build/reports/jacocoHtml
          if-no-files-found: ignore
          retention-days: 7
